remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_jpa_v2_2]
description: [Oracle Java Persistence API Technology Compatibility Kit User's Guide for Technology Licensees, Release 2.2]

# sidebar links url
links:
  source: https://github.com/javaee/tck_jpa_v2_2
  download: https://github.com/javaee/tck_jpa_v2_2/releases
  #mailinglist: https://javaee.groups.io/g/tck_jpa_v2_2
  #javadocs:
  docs: https://javaee.github.io/tck_jpa_v2_2
  #faq:

