remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_uml_v3_0]
description: [Oracle Technology Compatibility Kit User's Guide for Expression Language 3.0 for Technology Licensees, Release 3.0]

# sidebar links url
links:
  source: https://github.com/javaee/tck_uml_v3_0
  download: https://github.com/javaee/tck_uml_v3_0/releases
  #mailinglist: https://javaee.groups.io/g/tck_uml_v3_0
  #javadocs:
  docs: https://javaee.github.io/tck_uml_v3_0
  #faq:

