remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_jstl_v1_2]
description: [Oracle Technology Compatibility Kit User's Guide for A Standard Tag Library for JavaServer Pages (JSTL) 1.2 for Technology Licensees, Release 1.2]

# sidebar links url
links:
  source: https://github.com/javaee/tck_jstl_v1_2
  download: https://github.com/javaee/tck_jstl_v1_2/releases
  #mailinglist: https://javaee.groups.io/g/tck_jstl_v1_2
  #javadocs:
  docs: https://javaee.github.io/tck_jstl_v1_2
  #faq:

