remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_security_v1_0]
description: [Oracle Java EE Security API 1.0 Technology Compatibility Kit User's Guide for Technology Licensees, Release 1.0]

# sidebar links url
links:
  source: https://github.com/javaee/tck_security_v1_0
  download: https://github.com/javaee/tck_security_v1_0/releases
  #mailinglist: https://javaee.groups.io/g/tck_security_v1_0
  #javadocs:
  docs: https://javaee.github.io/tck_security_v1_0
  #faq:

