remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_coa_v1_3]
description: [Jakarta EE Technology Compatibility Kit User's Guide for Jakarta Annotations, Release 3.0]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/common-annotations-api
  download: https://github.com/eclipse-ee4j/common-annotations-api/releases
  #mailinglist: https://javaee.groups.io/g/tck_coa_v1_3
  #javadocs:
  docs: https://jakarta.ee/specifications/annotations/3.0
  #faq:
