remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_jms_v2_0]
description: [Oracle Technology Compatibility Kit User's Guide for Java Message Service 2.0 for Technology Licensees, Release 2.0]

# sidebar links url
links:
  source: https://github.com/javaee/tck_jms_v2_0
  download: https://github.com/javaee/tck_jms_v2_0/releases
  #mailinglist: https://javaee.groups.io/g/tck_jms_v2_0
  #javadocs:
  docs: https://javaee.github.io/tck_jms_v2_0
  #faq:

