remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [cts_javaee_v8_0]
description: [Eclipse Jakarta EE Platform, Test Compatibility Kit User's Guide for Technology Implementers, Release 10]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/jakartaee-tck
  download: https://github.com/eclipse-ee4j/jakartaee-tck
  mailinglist: https://accounts.eclipse.org/mailing-list/jakartaee-tck-dev
  #javadocs:
  docs: https://github.com/eclipse-ee4j/jakartaee-tck
  #faq:

