remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_coa_v1_3]
description: [Oracle Technology Compatibility Kit User's Guide for Common Annotations for the Java Platform 1.3 for Technology Licensees, Release 1.3]

# sidebar links url
links:
  source: https://github.com/javaee/tck_coa_v1_3
  download: https://github.com/javaee/tck_coa_v1_3/releases
  #mailinglist: https://javaee.groups.io/g/tck_coa_v1_3
  #javadocs:
  docs: https://javaee.github.io/tck_coa_v1_3
  #faq:

