remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_jsonb_v1_0]
description: [Oracle Technology Compatibility Kit User's Guide for Java API for JSON Binding 1.0 for Technology Licensees, Release 1.0]

# sidebar links url
links:
  source: https://github.com/javaee/tck_jsonb_v1_0
  download: https://github.com/javaee/tck_jsonb_v1_0/releases
  #mailinglist: https://javaee.groups.io/g/tck_jsonb_v1_0
  #javadocs:
  docs: https://javaee.github.io/tck_jsonb_v1_0
  #faq:

